import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';
import Logo from '../public/logo.ico';
import User from '../public/User.ico';
import Arrow from '../public/black_arrow.ico';
import Search from '../public/search.ico';




const head = () => {
  return (
    <>
      <Head>
        <title>Hype Industry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>



        <Navbar expand="lg" className='bg-light'>
          <Container>
            <Image src={Logo} alt="Picture" className="rounded-2"></Image>
            <Navbar.Toggle aria-controls="basic-navbar-nav" />
            <Navbar.Collapse id="basic-navbar-nav">
              <Nav className="me-auto fw-bold  ">

 



                <Nav.Link href="#home" className='px-3 py-3'>HYPEINDUSTRY   <Image src={Arrow} alt=""></Image> </Nav.Link>
                <Nav.Link href="#link" className='px-3 py-3'>HYPE OFFER   <Image src={Arrow} alt=""></Image> </Nav.Link>
                <Nav.Link href="#link" className='px-3 py-3'>SHIPPING   <Image src={Arrow} alt=""></Image>  </Nav.Link>
                <Nav.Link href="#link" className='px-3 py-3'>SELLER REQUEST FORM</Nav.Link>






              </Nav>

              <div className=' me-auto fw-bold d-inline-flex '>


                <Nav.Link href="#link" className=' mx-5 py-3 d-inline '><Image src={User} alt="Picture"></Image>Login</Nav.Link>


                <div className=''>
                  <form className="d-flex py-2 " role="search">
                    <Image className='position-absolute my-2 mx-1' src={Search} alt="Picture" />
                    <input className="form-control me-2 px-4 border-light" type="search" id='sea' placeholder=' Brand,Models   ' aria-label="Search" />



                  </form>
                </div>

              </div>




            </Navbar.Collapse>
          </Container>
        </Navbar>

      </main>
    </>
  )
}


export default head;





